spring.datasource.url=jdbc:mysql://127.0.0.1:3306/benchmark_db?useSSL=false
spring.datasource.username=admin
spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=100
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
