version: '3.8'

services:
  server-python:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: server-python-post
    ports:
      - "8001:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: admin
      DB_PASS: secret
      DB_NAME: benchmark_db
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  server-node:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    container_name: server-node-post
    ports:
      - "8002:8002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: admin
      DB_PASS: secret
      DB_NAME: benchmark_db
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  server-php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: server-php-post
    ports:
      - "8003:8003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: admin
      DB_PASS: secret
      DB_NAME: benchmark_db
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  server-go:
    build:
      context: .
      dockerfile: Dockerfile.go
    container_name: server-go-post
    ports:
      - "8004:8004"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: admin
      DB_PASS: secret
      DB_NAME: benchmark_db
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  server-java:
    build:
      context: .
      dockerfile: Dockerfile.java
    container_name: server-java-post
    ports:
      - "8005:8005"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: admin
      DB_PASS: secret
      DB_NAME: benchmark_db
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
