version: '3.8'

services:
  server-go:
    build:
      context: .
      dockerfile: Dockerfile.go
    network_mode: host

  server-nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    network_mode: host

  server-python:
    build:
      context: .
      dockerfile: Dockerfile.python
    network_mode: host

  server-java:
    build:
      context: .
      dockerfile: Dockerfile.java
    network_mode: host

  server-php:
    build:
      context: .
      dockerfile: Dockerfile.php
    network_mode: host
